// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjhvsjqwgbouaxrczncz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qaHZzanF3Z2JvdWF4cmN6bmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjIxNTUsImV4cCI6MjA3MTk5ODE1NX0.dQ1XNVqgcellz6M9kEyqCACKiq_GJ9R7LftJz_GQIEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});